### ISSUE TITLE
Specify Start Offset on an Event Stream

### ISSUE THREAD

**Issue by ryan-theta** [CrowdStrike/gofalcon#79]
Hi,
Any chance of a start offstart specifier for the event streams api please? or guidance on how to set.
https://github.com/CrowdStrike/gofalcon/tree/main/falcon/client/event_streams
:)

**Comment by isimluk** [comment]
Hello @ryan-theta,

Thank You for raising this issue to my attention.

You are right that the start offset specifier is not available in the event_streams client you are referring to. That part of the code is however automatically & periodically generated, so I am hesitant to touch it directly.

There is high-level API (created by living humans) available as well. I suggest you prefer to use the high-level API for streaming. Here is the example how to use it: https://github.com/crowdstrike/gofalcon/blob/v0.2.5/examples/falcon_event_stream/main.go#L47-L89 

---
As You may not notice the high-level API is not using the offset as well. Yet. That is going to be fixed in #85.

**Comment by ryan-theta** [comment]
thanks @isimluk, offset start int is confirmed working. did introduce a breaking change (very easy fix)

was
stream, err := falcon.NewStream(context.Background(), falconClient, appName, availableStream)

now
stream, err := falcon.NewStream(context.Background(), falconClient, appName, availableStream, uint64(intStart))
